### ISSUE TITLE
授权逻辑看不懂

### ISSUE THREAD

**Issue by zicjin** [qwdigital/LinkWechat#1]
"如果需要将本产品在本地进行任何附带商业化性质行为使用，请联系项目负责人进行商业授权"

但是[GPL协议](https://github.com/qwdigital/LinkWechat/blob/master/LICENSE)清楚写着：
You may make, run and propagate covered works that you do not convey, without conditions so long as your license otherwise remains in force.

简单讲，公司自用这个软件用于运营目的，并没有售卖给他人。是否符合你们的协议？

**Comment by sxjangdongqin** [comment]
自运营也是商业行为，是需要我们授权的！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月22日(周六) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwdigital/LinkWechat] 授权逻辑看不懂 (Issue #1)




 
"如果需要将本产品在本地进行任何附带商业化性质行为使用，请联系项目负责人进行商业授权"
 
但是GPL协议清楚写着：
 You may make, run and propagate covered works that you do not convey, without conditions so long as your license otherwise remains in force.
 
简单讲，公司自用这个软件用于运营目的，并没有售卖给他人。是否符合你们的协议？

**Comment by zicjin** [comment]
GPL协议的第一个权力就是：基于任何目的，按你的意愿运行软件的自由。

那请你们不要再使用GPL协议。

**Comment by sxjangdongqin** [comment]
运行可以啊，没让你进行商用啊？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月23日(周日) 晚上8:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwdigital/LinkWechat] 授权逻辑看不懂 (Issue #1)




 
GPL协议的第一个权力就是：基于任何目的，按你的意愿运行软件的自由。
 
那请你们不要再使用GPL协议。

**Comment by zicjin** [comment]
“基于任何目的，按你的意愿运行软件的自由” 当然包括商业目的。
不看自己贴的[LICENSE](https://github.com/qwdigital/LinkWechat/blob/master/LICENSE)，起码看一下关于GPL协议的共识吧：[GNU通用公共许可证](https://zh.wikipedia.org/zh-cn/GNU%E9%80%9A%E7%94%A8%E5%85%AC%E5%85%B1%E8%AE%B8%E5%8F%AF%E8%AF%81)

你们可以起草使用一个或多个自己的协议，但前提是不能相互矛盾。现在明显是矛盾的，何况你们自己的“协议”也没有规范地写在LICENSE文件里。
